version: '3'

volumes:
  db:

services:
  portfolio_service_dev:
    image: node:18
    restart: no
    env_file: ".env"
    working_dir: /app
    volumes:
      - ./web:/app
    networks:
      - portfolio_network
    ports:
      - '${HOST_PORT}:${CONTAINER_PORT}'
      - '9229:9229'
    command: npm run dev

networks:
  portfolio_network:
    driver: bridge