version: '3'

volumes:
  db:

services:
  softup_siportfolio_service:
    image: node:18
    restart: no
    env_file: ".env"
    working_dir: /app
    volumes:
      - ./web:/app
    links:
      - database_portfolio_service
    ports:
      - '${HOST_PORT}:${CONTAINER_PORT}'
      - '9229:9229'
    command: npm run dev

  database_portfolio_service:
    image: postgres:15.2-alpine
    restart: no
    env_file: ".env"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'