version: '3'

volumes:
  db:

services:
  auth_server_traffic_box:
    image: node:18
    restart: always
    env_file: ".env"
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - database_auth_server_traffic_box
    ports:
      - '${APP_SOCKET_CONTAINER_PORT}:${APP_SOCKET_PORT}'
    command: npm run build && npm run start

  database_auth_server_traffic_box:
    image: postgres:15.2-alpine
    restart: always
    env_file: ".env"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'