version: '3'

volumes:
  db:

services:
  portfolio_service:
    image: node:18
    restart: always
    env_file: ".env"
    working_dir: /app
    volumes:
      - ./web:/app
    links:
      - database_portfolio_service
    ports:
      - '${HOST_PORT}:${CONTAINER_PORT}'
    command: npm run build && npm run start

  database_portfolio_service:
    image: postgres:15.2-alpine
    restart: always
    env_file: ".env"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'